server:
  port: 8180
#eureka:
#  instance:
#      prefer-ip-address: true
#      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: open-admin
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/openvive?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ENC(ifAMe4onLwMntr2Ol1jbyw==)
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 10
    max-active: 50
    max-wait: 60000
    validationgQuery: SELECT 'X'
    timeBetweenEvictionRunsMillis: 60000
  zipkin:
    base-url: http://127.0.0.1:9411
mybatis:
  type-aliases-package: com.vivebest.openvive.admin.domain,com.vivebest.openvive.common.domain
  mapper-locations: classpath*:mybatis/mysql/*.xml
#jasypt加密的密匙
jasypt:
  encryptor:
    password: openvivepassword
#token加密密钥 
token:
  secret: openvive2018
  
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                          timeout-in-milliseconds: 5000
